services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-teste-tecnico
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app_network
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge